name: Pull Request Greeting

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Lets Hacktober!'
        pr-message: 'Happy to have you onboard **#**'
